# Generated by Django 5.2.10 on 2026-01-09 21:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveDirectoryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sam_account', models.CharField(max_length=254, unique=True)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('display_name', models.CharField(max_length=508)),
                ('enabled', models.BooleanField(default=True)),
                ('sid', models.CharField(max_length=508, unique=True)),
                ('when_changed', models.DateTimeField()),
                ('given_name', models.CharField(blank=True, default=None, max_length=254, null=True)),
                ('upn', models.CharField(blank=True, default=None, max_length=508, null=True)),
                ('middle_name', models.CharField(blank=True, default=None, max_length=254, null=True)),
                ('employee_id', models.IntegerField(blank=True, default=None, null=True)),
                ('department', models.CharField(blank=True, default=None, max_length=254, null=True)),
                ('title', models.CharField(blank=True, default=None, max_length=254, null=True)),
                ('manager', models.CharField(blank=True, default=None, max_length=508, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('last_logon', models.DateTimeField(blank=True, default=None, null=True)),
                ('company', models.CharField(blank=True, default=None, max_length=254, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=508, null=True)),
                ('home_dir', models.CharField(blank=True, default=None, max_length=508, null=True)),
                ('home_drive', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('initials', models.CharField(blank=True, default=None, max_length=3, null=True)),
                ('mobile', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('office', models.CharField(blank=True, default=None, max_length=254, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=254, null=True)),
                ('zip_code', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('proxy_addresses', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=254), blank=True, default=list, null=True, size=None)),
                ('pwd_last_set', models.DateTimeField(blank=True, default=None, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=2, null=True)),
                ('street_address', models.CharField(blank=True, default=None, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('script', models.CharField(blank=True, default=None, max_length=254, null=True)),
                ('sur_name', models.CharField(blank=True, default=None, max_length=254, null=True)),
            ],
        ),
    ]
