# Generated by Django 5.2.10 on 2026-01-12 20:58

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activedirectoryuser',
            name='sam_account',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=254, unique=True)),
        ),
    ]
