# Generated by Django 5.2.10 on 2026-01-12 21:13

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_users', '0002_alter_activedirectoryuser_sam_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activedirectoryuser',
            name='sam_account',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=254)),
        ),
    ]
